name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        board: ["asterix"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: pebble-hwv

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: pebble-hwv
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: pebble-hwv
        run: |
          west build -b ${{ matrix.board }} app

      - name: Prepare artifacts
        working-directory: pebble-hwv
        run: |
          mkdir artifacts
          cp build/zephyr/zephyr.hex artifacts/pebble-hwv_${{ matrix.board }}_${{ github.ref_name }}.hex

      - name: Store hex files
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.board }}
          path: pebble-hwv/artifacts

  release:
    runs-on: ubuntu-24.04

    needs: build
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Display artifacts
        run: ls -R

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts-*/*
